### PR TITLE
Drop Phing for Makefile

### PR DESCRIPTION
**Pull request by Kocal**
See https://github.com/phpstan/phpstan-symfony/pull/160

### CODE REVIEW

**Comment by williamdes** [comment]
Good job on the `.gitattributes` file !
The folder `build-cs` is missing and `.editorconfig` is also missing

**Comment by ondrejmirtes** [comment]
@williamdes Please send a PR.

**Comment by ondrejmirtes** [comment]
And maybe check the other repositories too :)

**Comment by williamdes** [comment]
> And maybe check the other repositories too :)

I am building a big tool and when it will be ready I will fire it on some orgs to do some cleanup ;)
Manual clone + edit + push + PR is time consuming and a bot/script is able to do that quicker than me, anyway I will let you know

**Pull request merged**
